// BiblioKeia themes
import theme from "assets/theme";

// @mui material components
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";

import Head from "next/head";

import Navbar from "./Navbar";

// Routes
import routes from "routes";

export default function LayoutOpac({ children }) {
  return (
    <>
      <Head>
        <title>BiblioKeia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        <CssBaseline />
      {/*   <Navbar
          routes={routes}
          action={{
            type: "external",
            route: "https://www.creative-tim.com/product/material-kit-react",
            label: "login",
            color: "info",
          }}
          sticky
        /> */}
        <main>{children}</main>
      </ThemeProvider>
    </>
  );
}
